#!/bin/bash
# $Id: rhost,v 1.28 2016/02/10 10:51:51 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/rhost,v $
# $Release$
# Author C W Fulford.
# Copyright 2013 (c) C W Fulford. All rights reserved.
# For assistance contact fulford@fulford.net 0709 229 5385
###################################################################
cmd=`basename $0`
syntax="$cmd [-c <config file>] [-l <login name>] [-v] <hostname>\nor\n
 <hostname> [-c <config_file>] [-l <login_name>] [-v] <hostname>"
while [ $# -gt 0 ];do
	case $1 in
		-c) config=$2;shift 2;;
		-d) set -x;debug=:;shift;;
		-l) login="-l $2";shift 2;;
		-v) set -x;sshv="-v";shift;;
		-X) xforward=:;shift;;
		-*) echo -e $syntax >&2; exit;;
		 *) host=$1;shift;;
	esac
done
config=${config:-/usr/local/etc/rhost.cf}
bg=${bg:-yellow}
fg=${fg:-blue}
port=22
vterm=${vter:-xterm}

if [ -z $host ];then
	host=`basename $0`
fi	
if [ $host = "host" ];then
	echo "$0: host not set connecting to localhost" >&2
	host=localhost
fi
if [ -f "$config" ] ;then
	if grep "^$host:"  $config >/dev/null 2>&1 ;then 
		eval `sed -ne "/^$host:/,/^$/{
			/^[ 	][^#]/p
		}" $config`
	else
		echo "$cmd: $host not found in $config" >&2
	fi
else
	echo "$cmd: $config not found" >&2
fi
[ $xforward ] && params="$params -X"
[ $verbose ] && echo $params >&2

ping -c 1 -W 1 $host >/dev/null ||{
	case $conn in
		vpn) vn-connect ${debug:+"-d"} $host;teardown="killall pppd";;
	esac
}

case $vterm  in 
	   xterm) $vterm -display :0.0 -bg $bg -fg $fg -T $host -geometry 80x24 -fs 10 -e "ssh $sshv -p $port $login $host";;
	terminal) $vterm --title=$host -e "ssh $login -p $port $host";;
esac
[ $teardown ] && $teardown
